server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/security?serverTimezone=Asia/Seoul
    username: cos
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 679225567034-baqo8esg0t172nm83t4kpb1h3cjlahv1.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 157234910687032
            client-secret: 103a58152d9b75a53ddfa9f361d1a057
            scope:
              - email
              - public_profile

          naver:
            client-id: hCdhjIkIF1fyZNmLBqZr
            client-secret: gWeTu1CBPR
            scope:
              - name
              - email
#              - profile-image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
